name: CI w Emscripten

# Only trigger workflow when code changes, or this file is changed.
# Android has a different workflow and different rules.
on:
  push:
    paths:
      - "desktop_version/CMakeLists.txt"
      - "desktop_version/src/**.cpp"
      - "desktop_version/src/**.c"
      - "desktop_version/src/**.h"
      - "third_party/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "desktop_version/CMakeLists.txt"
      - "desktop_version/src/**.cpp"
      - "desktop_version/src/**.c"
      - "desktop_version/src/**.h"
      - "third_party/**"
      - ".github/workflows/ci.yml"

env:
  SRC_DIR_PATH: desktop_version

jobs:
  build-em:
    name: Build (Steam Linux Runtime Sniper w Emscripten)

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Dependancies
      run: |
        sudo apt install ninja-build
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
    - name: CMake configure (default version)
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        mkdir data
        cp -r ../fonts ./data/fonts
        cp -r ../lang ./data/lang
        cp ../data.zip ./data/data.zip
        emcmake cmake -G Ninja ..
    - name: Build (default version)
      run: ninja -C ${SRC_DIR_PATH}/build

    - name: Upload engine (artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: artifact-vvvvvv
        path: |
          ./desktop_version/build/*
          !./desktop_version/build/*.o
  download:
    needs: build-em
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ghpages
    - name: Setup Node & NPM
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ./
        pattern: artifact-*
        merge-multiple: true
    - name: Push to GH Pages
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GH Pages as per master branch"
          git push
      

